/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ScientificCalculator calc = new ScientificCalculator();
        int result= calc.modulo(5, 2);
        System.out.println("modulo =" + result);

        // double result= calc.cubeOf(4.0);
        // System.out.println("cube =" + result);

        /*
        StandardCalculator calc = new StandardCalculator();
        calc.add(1,2);
        System.out.println(calc.getResult());

        calc.subtract(2,1);
        System.out.println(calc.getResult());

        calc.multiply(2,2);
        System.out.println(calc.getResult());

        calc.divide(6,2);
        System.out.println(calc.getResult()); */
    }
}
